import createClient from 'openapi-fetch';
import type { paths } from './frontend-api-schema'; // generated by openapi-typescript

export const apiClient = createClient<paths>({ baseUrl: 'http://localhost:3003' });
